### ISSUE TITLE
Please add wheels for Python 3.9

### ISSUE THREAD

**Issue by wichert** [capnproto/pycapnp#235]
This removes the need for everyone using Python 3.9 to compile libcapnp and pycapnp.

**Comment by haata** [comment]
I'll see if I can work on this.

**Comment by haata** [comment]
Linux wheels build fine: https://github.com/capnproto/pycapnp/actions/runs/344926671
Though I will need to look into the Windows build because something seems to have changed as is no longer building (might be capnproto-0.8.0 related): https://github.com/capnproto/pycapnp/runs/1351257082?check_suite_focus=true

**Comment by wichert** [comment]
How are macOs builds made? Are those a manual process?

**Comment by haata** [comment]
No, I pull the artifacts generated by the GitHub actions and then upload them to PyPi (manually).

**Comment by fvannee** [comment]
The binary packages for Windows 3.9 would be great to have indeed. Thanks for looking into it!

**Comment by haata** [comment]
I've made some discoveries/conclusions and I now have a 100% passing CI
https://github.com/capnproto/pycapnp/runs/1429465417?check_suite_focus=true

If I have some time tomorrow I'll upload a 1.0.0b2 for Python 3.9. Though I might just do an official 1.0.0.

**Comment by haata** [comment]
https://pypi.org/project/pycapnp/1.0.0/#files

Should have everything you need now.
I'm currently not packaging 32-bit packages for Windows, so make sure you're using 64-bit Python 3.9.

**Comment by wichert** [comment]
Thank you!
