### ISSUE TITLE
Text type causes difficulties for code that supports both py2 and py3

### ISSUE THREAD

**Issue by mikelundy** [capnproto/pycapnp#92]
I'm just getting started with capnp, so I'll apologize up front for anything that stems from ignorance. I work on code that supports on both python2 and python3, and the (relatively small) asymmetry between read and write and unicode causes a bit of a complexity in using it.

So, pycapnp expects that all strings written to or read from Text types are the current python `str` (which, to be clear, I don't actually consider to be a bad default). In projects trying to target py2 and py3 at the same time, though, generally you'd put `from __future__ import unicode_literals` at the top of everything and do your level best to pretend the py2 `unicode` was actually `str`. This methodology actually works pretty well for consistent behavior on both platforms, modulo a few edge cases which these helpers solve:

``` python
def ensure_text(data, encoding='utf-8'):
    if isinstance(data, six.text_type):
        return data
    elif isinstance(data, six.binary_type):
        return data.decode(encoding)
    raise ValueError('cannot ensure_text from type %r' % (type(data,)))

def ensure_native_str(data, encoding='utf-8'):
    if isinstance(data, str):
        return data
    elif six.PY2 and isinstance(data, six.text_type): # py2 "unicode"
        return data.encode(encoding)
    elif six.PY3 and isinstance(data, six.binary_type): # py3 "bytes"
        return data.decode(encoding)
    raise ValueError('cannot ensure_native_str from type %r' % (type(data,)))
```

You can probably see the problem I've been roundabout at describing now, which is that every single assignment into or extraction from a Text field in pycapnp requires the use of these above helpers to maintain consistent behavior across both major versions if you've committed to the unicode_literals model.

So, what I guess I'm asking for is some way to choose the translation function between the utf-8 bytes that are contained inside the capnp messages and the string that is presented on the python side; right now, pycapnp runs (basically) the logical equivalent of `six.text_type.encode(input_string, 'utf-8')` when writing into a Text field, and `six.binary_type.decode(field_string, 'utf-8')` when extracting from it; for my purpose, it would be much more convenient if i could do one of two things: 1) allow me to change the translation functions myself, which would let me use the unicode type in py2 and would let me completely disable translation if necessary (always writing and returning the bytes() type) or 2) disable the translation layer entirely, exposing the capnp Text field exactly as specced with no translation (i.e. it is _always_ the bytes() type). Obviously, I'd prefer the former (since it's basically the generalization of the latter), but the latter could work (and has the advantage that it'd actually probably be slightly faster, since it's returning the actual bytes with no translation).

Anyway, thoughts?

**Comment by jparyani** [comment]
Let me just say, I really hate the difference between Python 2 and Python 3 strings :)

In retrospect, I agree. I probably should've made all Text fields be bytes, even under Python 3. It would make Python 3 code using pycapnp uglier though, so there's something to be said for the current behavior. Unfortunately, this would be a huge breaking change, so I don't think it'll happen going forward.

I'm somewhat amenable to your other proposal of adding someway to specify the encoding. The major problem is that I can't think of a good way to control the scope and be performant. Say you make some library (let's call it library A) that depends on pycapnp, and then library B comes along and sets the default encoding to something you don't expect. pycapnp could maybe let you specify it at load/import time of a .capnp file, but then it becomes this state that needs to trickle down to every struct that comes from that module and needs to be checked every time you access a Text field. It could also be an annotation that lives in the .capnp file (similar to C++ namespace annotations https://github.com/sandstorm-io/capnproto/blob/96ef3a3b9b86331261c7d515b3acf793b68595ad/c%2B%2B/samples/addressbook.capnp#L25).

Overall, I'm hesitant to commit to this, since I'd definitely want to do it in such a way that adds a minimum amount of overhead to the current code path.

**Comment by mikelundy** [comment]
Again, please excuse any gaps in my knowledge of how this works, I'm reading the code of both capnp and pycapnp but I don't think I'm well-versed in it yet.

Hm, I can see the potential for the annotation approach to be clean, though it feels slightly wrong from a scoping perspective (namespace feels like a property of the message itself, but the interpretation of the strings feels like it exists at a different scope). Perhaps this can be done as a configuration (or perhaps sub/sibling class) of the Reader and the Builder, with the choice of the Reader or Builder type being handled by kwargs on read or new_message, respectively? That at least feels like it's scoping the choice of string interpretation to the thing that cares most, namely, the thing that is actually instantiating the message? (This way, if I made a stupid choice in my server, that choice wouldn't propagate to people writing clients like it probably would if it were handled via annotation)

Careful choices in the implementation of the new Reader and Builder could mean this would cost only one additional branch in the instantiation path (taken either once at read time if the work is handled by a new Builder class, or taken per text field read if it's handled via configuration of the existing Builder).

**Comment by jparyani** [comment]
You're right, it could be an argument to new_message/read, and branch there. This still leaves the RPC code paths, but I'm ok with ignoring them for now (and they could grow to have the same argument too I guess).

Unfortunately, I don't have a lot of time to devote to this, but if you or someone else submitted a PR, I'd be happy to merge :)

**Comment by chaoflow** [comment]
@novas0x2a May I ask whether you found a way to receive ``unicode`` in contrast to ``str`` for ``Text`` fields from capnp under Python 2?

**Comment by novas0x2a** [comment]
ah, nope, we never ended up moving forward with it.

**Comment by haata** [comment]
Python 2 is no longer supported.
